services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_BASE_URL=http://localhost:8081
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./backend:/api
      - /api/node_modules
    networks:
      - todos-network
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo-container:27017/todosDB
  mongo:
    image:  mongo
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - todos-network
  
    
networks:
  todos-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local